### ISSUE TITLE
gas station

### ISSUE THREAD

**Issue by kikipluche** [swarmcity/sc-boardwalk#31]
_From @kikipluche on February 1, 2017 9:16_

exchanging SWT for ETH to pay for transactions

_Copied from original issue: swarmcity/sc-terminal#64_

**Comment by sponnet** [comment]
Gas-Station
Goal: A third party payer system for exchanging SWT to ETH to gover for gas costs in the Ethereum network.

glassary: 
SWT = Swarm City token

Method: 
An allowance for 1 swt to the Gas-Station transaction is created by the sender and is signed locally on his device. 
This transaction is sent to the Gas-Station API over http ( = a centralised node which can be a decentralized farmer app later on )
The API logic send gas (ETH) to perform this TX to the pub key of the sender and immediately executes the signed transaction from the allowance call by sending it to the Ethereum network via its local node ( eth.swarm.city ) 
When the Gas-station contract receives the SWT - it triggers a conversion function that calculates how much gas this SWT is worth. The amount of ETH that is sent back = swt/eth ratio * .9 - gas first tx * gas-price - gas * gas-price for sending eth to pub key
The swt/eth ratio is read from an oracle variable inside the contract and is updated with every refill of ETH by the gas-station server.
The ratio is raised with 10% so that it will never be used to buy ETH from the contract. It is just a method of bootstrapping gas-less clients.

**Comment by kikipluche** [comment]
diagram made by Jam10o, as a solution for the same issue, this is informative, could be interesting to compare to the solution as described above
[SWTGas-stop.pdf](https://github.com/swarmcity/sc-boardwalk/files/978460/SWTGas-stop.pdf)

**Comment by kikipluche** [comment]
this will be solved in a different way, will be in new issue
